fix: could not find the Electron app binary at
could not find the Electron app binary at "/home/runner/work/TiddlyGit-Desktop/TiddlyGit-Desktop/out/TiddlyGit-linux-x64/tiddly-git". You may need to re-bundle the app using Electron Packager's "executableName" option.
Error: could not find the Electron app binary at "/home/runner/work/TiddlyGit-Desktop/TiddlyGit-Desktop/out/TiddlyGit-linux-x64/tiddly-git". You may need to re-bundle the app using Electron Packager's "executableName" option.

https://stackoverflow.com/questions/57115803/error-showing-while-creating-a-debian-file-from-electronjs-project