chore: only use cache in mac, since windows often have cache issue
Error: Cannot find module 'undefinedbuild/Release/registry.node'
Require stack:
- E:\repo\TiddlyGit-Desktop\.webpack\main\index.js
- E:\repo\TiddlyGit-Desktop\node_modules\electron\dist\resources\default_app.asar\main.js

Fixed by delete .webpack and node_modules/.cache