fix: Webpack has been initialized using a configuration object that does not match the API schema
An unhandled error has occurred inside Forge:
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.plugins[6] should be one of these:
   object { apply, … } | function
   -> Plugin of type object or instanceof Function.
   Details:
    * configuration.plugins[6] should be an object:
      object { apply, … }
      -> Plugin instance.
    * configuration.plugins[6] should be an instance of function.
      -> Function acting as plugin.
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.plugins[6] should be one of these:
   object { apply, … } | function
   -> Plugin of type object or instanceof Function.
   Details:
    * configuration.plugins[6] should be an object:
      object { apply, … }
      -> Plugin instance.
    * configuration.plugins[6] should be an instance of function.
      -> Function acting as plugin.

This is because there is an undefined in the plugins list

exports.renderer [
  DefinePlugin {
    definitions: { 'process.env.NODE_ENV': '"development"' }
  },
  CspHtmlWebpackPlugin {
    cspPluginPolicy: {
      'base-uri': [Array],
      'object-src': [Array],
      'script-src': [Array],
      'style-src': [Array],
      'frame-src': [Array],
      'worker-src': [Array]
    },
    opts: {
      enabled: true,
      hashingMethod: 'sha256',
      hashEnabled: [Object],
      nonceEnabled: [Object],
      processFn: [Function: defaultProcessFn]
    }
  },
  WebpackBarPlugin {
    profile: false,
    handler: [Function (anonymous)],
    modulesCount: 5000,
    dependenciesCount: 10000,
    showEntries: true,
    showModules: true,
    showDependencies: true,
    showActiveModules: true,
    percentBy: undefined,
    options: {
      name: 'webpack',
      color: 'green',
      reporters: [Array],
      reporter: null
    },
    reporters: [ FancyReporter {} ]
  },
  undefined
]